### ISSUE TITLE
Import scss files from node_modules

### ISSUE THREAD

**Issue by rafaelbastiansch** [Anidetrix/rollup-plugin-styles#131] opened 2020-07-23 15:40 UTC
Can't I import scss files from packages inside node modules?

I can import css files like this
`@import '~vuetify/dist/vuetify.css';`

but when I tried to import scss files like this
`@import '~vuetify/src/styles/generic/_colors.scss';`
it doesn't work, and give me an error
`Can't find stylesheet to import.
@import '~vuetify/src/styles/generic/_colors.scss';`

Is there any way to import pre compiled style files?

**Comment by Anidetrix** [comment] 2020-07-23 15:59
Hi @rafaelbastiansch,

Unfortunately, I could not reproduce your issue.

> @import '~vuetify/src/styles/generic/_colors.scss';

Worked for me just fine (although it gave errors about undefined variables, but this seems to be unrelated to the case).

So it seems that I'll need a minimal reproduction repo for this. Can you make one using [rollup's REPL](https://rollupjs.org/repl/), [REPL.it](https://repl.it/@rollup/rollup-repro), or just GitHub repo?

**Comment by rchl** [comment] 2020-10-07 19:01
I believe I also had an issue like that but importing from JS file using `import` worked fine. Try it out if that's an option for you.

**Comment by Anidetrix** [comment] 2020-12-28 03:47
@rchl If you encounter it again, please make minimal reproduction repo is possible.

**Comment by Anidetrix** [comment] 2020-12-28 06:38
@rafaelbastiansch @rchl  Closing this for now, please reopen if you encounter this problem again.

**Closed** 2020-12-28 17:42 UTC
Labels: question
