### ISSUE TITLE
In `preserveModules` mode, the emitted style file will be overwritten and the position is not correct 

### ISSUE THREAD

**Issue by RunningCoderLee** [Anidetrix/rollup-plugin-styles#120] opened 2020-06-11 09:18 UTC
In `preserveModules` mode, if there are files with the same name in different folders, the emitted style file will be overwritten。

```
src/
  |- components/
  |       |- Card/
  |       |   |- styles/
  |       |   |    |- index.scss
  |       |   |- Card.tsx
  |       |   |- index.ts
  |       |- index.ts
  |- styles/
  |    |- public.scss
  |- index.ts
```

```ts
// src/components/Card/Card.tsx
import './styles/index.scss

function Card() {
// ...
}

export default Card
```

```ts
// src/components/Card/index.ts
import Card from './Card'

export default Card
```

```ts
// src/components/index.ts
import '../styles/public.scss'

export { default } from './Card'
```

```ts
// src/index.ts
export * from './components'
```

```js
// rollup.config.js

export default {
  input: 'src/index.ts',
  preserveModules: true,
  output: [
    {
      dir: 'build/es',
      format: 'es',
      assetFileNames: '[name][extname]',
      chunkFileNames: '[name].js',
      entryFileNames: '[name].js',
      minifyInternalExports: false,
    },
  ],
  plugins: [
    typescript({
      ...
    }),
    styles({
      mode: 'extract',
      url: {
        inline: true,
      },
      sass: {
        impl: 'sass',
        fiber: require('fibers'),
      },
    }),
  ],
}
```

After bundle:

```
build/
  |- es/
      |- components/
      |        |-Card/
      |             |- Card.js
      |             |- index.js
      |- index.css
      |- index.js
```

Expected: 

```
build/
  |- es/
      |- components/
      |        |-Card/
      |             |- Card.css
      |             |- Card.js
      |             |- index.js
      |- index.css
      |- index.js
```

**Comment by Anidetrix** [comment] 2020-06-11 11:46
Hi @RunningCoderLee, thank you for dedicating time for this issue!

Unfortunately, I could not reproduce your problem, could you please provide a reproduction repo using something like [rollup's REPL](https://rollupjs.org/repl/), [REPL.it](https://repl.it/@rollup/rollup-repro), or just GitHub repo

P.S. `fiber` option is overwritten internally, I'll make it clearer in the next update, use `fibers` option instead

**Comment by Anidetrix** [comment] 2020-06-11 12:31
With my attempt to reproduce the issue i got: 

```bash
build/es
├── Card.css
├── components
│   ├── Card
│   │   ├── Card.js
│   │   └── index.js
│   └── index.js
├── index.css
└── index.js
```

**Comment by RunningCoderLee** [comment] 2020-06-11 14:00
Thank you for your reply.

Here is a demo repo and you can run `npm run build` to reproduce this problem

https://github.com/RunningCoderLee/rollup-plugin-styles-demo

**Comment by Anidetrix** [comment] 2020-06-11 17:38
Hi again @RunningCoderLee!

I was able to reproduce the issue using the provided repo, and also was able to determine why was the file not present/overwritten (is it due to Map usage, replaced it with array locally and now everything is fine, will be in the next release).

As of `Card.css` nesting, [your PR](https://github.com/Anidetrix/rollup-plugin-styles/pull/121) is still applicable, but I have noted some changes there which should be changed before I merge it, or I can just close it and add them myself (with author's notice) if you want.

**Closed** 2020-06-11 22:32 UTC
